swagger: "2.0"
info:
  title: "Employees API"
  description: "API diseñada para gestionar empleados utilizando Flask y MongoDB."
  version: "1.0.0"
host: "localhost:8000"
basePath: "/"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions: {}
